
<?php
include("header.php");
include("header-bottom.php");
?>

        
<div id="body-content" style="background: #f0f0f0;">
               <div id="main-content">
                  <div class="main-content">
                     <div id="home-main-content" class="">
                       
                     
<div class="bg-secondary py-4">
      <div class="container d-lg-flex justify-content-between py-2 py-lg-3">
        <div class="order-lg-2 mb-3 mb-lg-0 pt-lg-2">
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb flex-lg-nowrap justify-content-center justify-content-lg-start">
              <li class="breadcrumb-item"><a class="text-nowrap col-white" href="index"><i class="fa fa-home"></i> Home</a></li>
              <li class="breadcrumb-item text-nowrap"><a href="#" class="col-white" style="background: transparent;">Help center</a>
              </li>
              <li class="breadcrumb-item text-nowrap active col-white" aria-current="page">COOKIES POLICY
              </li>
            </ol>
          </nav>
        </div>
        <div class="order-lg-1 pr-lg-4 text-center text-lg-left">
          <h1 class="h3 mb-0 col-white">COOKIES POLICY</h1>
        </div>
      </div>
    </div>

     <!-- Page Content-->
    <div class="container py-5 mt-md-2 mb-2">
      <div class="row">

 <div class="col-lg-9">
<p><strong>What are cookies?</strong></p>

<p>Cookies are small files that can be used to store certain information that you, as a user, have already provided while browsing the website. The <?php  echo $set['storeName']; ?> website uses cookies to remember your preferences (for example, it can remember which page you visited, in order to make your next visit more comfortable by showing you information about what you have previously visited). These cookies are sent to your browser and stored on your computer. However, you can choose the cookie settings through our "Cookie Settings" panel and even if you do not want to install any cookies, except the strictly necessary ones that allow you to access the <?php  echo $set['storeName']; ?> website in a basic way and are necessary for your operation, you can disable them at any time through the same panel "Cookie settings".</p>

<p><strong>How do we use COOKIES at <?php  echo $set['storeName']; ?>?</strong></p>

<p>The <?php  echo $set['storeName']; ?> website uses cookies. This information, once collected, is analyzed for different purposes, mainly in order to improve and optimize your browsing experience (for example, first showing those products that may interest you the most).</p>

<p><strong>Examples of how we use cookies</strong></p>

<p>To calculate the number of visitors who access our website and ensure that there is enough capacity to make it fast. To improve the functioning of the website, for example, by ensuring that users easily find what they are looking for. To guarantee the functionality of certain services. To recognize your login details so you don't have to enter them on every page you want to view. To show you ads according to the navigation you have made on the web and your profile in a more personalized way.</p>

<p>For the operation of cookies, <?php  echo $set['storeName']; ?> uses an ID identifier that is not associated with personal data, so we cannot individually identify customers who browse the web, except in the case that we explain below.</p>

<p><strong>Google Analytics service</strong></p>

<p>This website uses Google Analytics, a web analysis service of Google Inc. (“Google”). Google Analytics uses "Cookies", text files, which are stored on the user's computer and allow an analysis of the use of the website. The information generated by the cookie about the use of this website by users is usually transferred and stored to a Google server in the USA Google counts as a guarantee for international data transfers with adherence to the Privacy Shield ( Privacy Shield).</p>

<p>Google will use this information on request also to evaluate the use of the website by users, compiling reports on the activity of the website and will provide other services related to the use of the website and the internet.</p>

<p>In the event that, on the occasion of the use of cookies, it is necessary to carry out an international transfer of data, we will adopt the appropriate legal measures and sign the corresponding standard clauses.</p>

<p><strong>What types of cookies do we use?</strong></p>

<p>The cookies that we use at www.<?php  echo $set['storeName']; ?>.es to improve your experience as a customer are the following:</p>

<p>Strictly necessary cookies: These cookies are necessary for the website to function and cannot be disabled in our systems. They are generally only set in response to your actions taken when requesting services, such as setting your privacy preferences, logging in, or filling out forms. You can configure your browser to block or alert about these cookies, but some areas of the site will not work. These cookies do not store any personally identifiable information.</p>

<p>Analytical cookies: These cookies allow us to count visits and traffic sources in order to evaluate the performance of the site and improve it. They help us to know which pages are the most or least visited and how visitors navigate the site. If you do not allow the use of this cookie, we will not know when you visited the site and we will not be able to evaluate whether it worked correctly.</p>



<p>Many cookies are "session", which means that they will disappear as soon as you end the session (when you close the browser). Other cookies are permanent, which means that they will be stored on your computer for a period of time.</p>

<p><strong>How can you configure cookies and revoke consent?</strong></p>

<p>When you access our website for the first time, you are shown a window in which you are asked to indicate whether you accept cookies or whether you want to configure them, except those strictly necessary, through the Cookie Settings panel.</p>

<p>If you wish to configure them, you can access the Cookie Configuration panel where you will see the type of cookies with which we work and their function and thereby choose the installation of the cookies of your choice.</p>

<p>If you accept third-party cookies and later wish to delete them, you can use the cookie deactivation tools of the different browsers or through the system enabled by these third parties to do so through the links that we indicate in the next section.</p>

 

<p><strong>How to disable cookies in the main browsers</strong>
 
<p>To disable cookies, you simply have to modify your browser settings. For more information, you can visit the cookie deactivation guidelines provided for any of the four most used browsers: Google Chrome, Mozilla Firefox, Internet Explorer, Safari, Safari for IOS (iPhone and iPad), Chrome for Android, Chrome for Iphone and Ipad.</p>
<p>There are also options to disable Google Analitycs, which you can find here</p>

 </div>
  </div>
</div>





</div>
</div>
</div>
</div>


<?php
//include("footer-newsletter-section.php");
//include("footer-section-two.php");
//include("footer-partners.php");
include("footer-bottom.php");
?>